// Code generated by @wagmi/cli via `pnpm contracts:generate` — DO NOT EDIT.
// Source: conflux-contracts/wagmi.config.ts → artifacts/contracts/
//
// Re-exports the generated type-safe ABI constants under the legacy names
// used throughout the SDK and CAS worker.

export {
  automationManagerAbi as AUTOMATION_MANAGER_ABI,
  swappiPriceAdapterAbi as SWAPPI_PRICE_ADAPTER_ABI,
  permitHandlerAbi as PERMIT_HANDLER_ABI,
  automationManagerAbi,
  swappiPriceAdapterAbi,
  permitHandlerAbi,
} from './generated.js';
