packages:
  - conflux-sdk
  - conflux-contracts
  - conflux-cas
  - conflux-cas/shared
  - conflux-cas/backend
  - conflux-cas/worker
  - conflux-cas/frontend
ignoredBuiltDependencies:
  - keccak
onlyBuiltDependencies:
  - better-sqlite3
  - bufferutil
  - esbuild
  - secp256k1
  - utf-8-validate
